### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Flow

### ISSUE THREAD

**Issue by ayaz-amin** [VLL-HD/FrEIA#15]
Hi there! I have a problem with loading my model. Here is my [training script](https://colab.research.google.com/drive/1eP9mk_-nCHCvJfkh7LPgTa62dPb6CjtI#scrollTo=NJils7V815lS).

All works well except when trying to load the model. I tried saving and loading a blank ```state_dict```, which works. But it returns an error when I load the trained model.

Here is the script that I want to load the ```state_dict``` into:

```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision.models.squeezenet import Fire
import FrEIA.framework as Ff
import FrEIA.modules as Fm

class Flow(nn.Module):
    def __init__(self, shape, num_steps):
        super(Flow, self).__init__()
        self.C, self.H, self.W = shape
        self.num_steps = num_steps
        self.model = self.build_model()

    def build_model(self):
        def subnet(in_channels, out_channels):
            return nn.Sequential(
                Fire(in_channels, 16, 8, 8),
                nn.BatchNorm2d(16),
                Fire(16, 8, 16, 16),
                nn.BatchNorm2d(32),
                Fire(32, 16, out_channels // 2, out_channels // 2)
            )
        
        nodes = [Ff.InputNode(self.C, self.H, self.W, name='input')]

        nodes.append(Ff.Node(nodes[-1], Fm.HaarDownsampling, {}, name='downsample'))

        for i in range(self.num_steps):
            nodes.append(Ff.Node(nodes[-1], Fm.PermuteRandom, {'seed':i}, name='permute_{}'.format(i)))
            nodes.append(Ff.Node(nodes[-1], Fm.GLOWCouplingBlock, {'subnet_constructor':subnet}, name='couple_{}'.format(i)))

        nodes.append(Ff.OutputNode(nodes[-1], name='output'))
        
        return Ff.ReversibleGraphNet(nodes, verbose=False)

    def forward(self, x):
        z = self.model(x)
        log_det = self.model.log_jacobian(run_forward=False)
        return z, log_det

    def generate(self, x):
        return self.model(x, rev=True)

    def reconstruct(self, x):
        return self.model(self.model(x), rev=True)      

net = Flow((3, 32, 32), 3)
net.load_state_dict(torch.load('flow.pt', map_location=torch.device('cpu')))
```
And this is the error that comes up:

```
Traceback (most recent call last):
  File "c:/Users/AyazA/Desktop/project/squeezeglow.py", line 55, in <module>
    net.load_state_dict(torch.load('flow.pt', map_location=torch.device('cpu')))
  File "C:\Python37\lib\site-packages\torch\nn\modules\module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Flow:
        Unexpected key(s) in state_dict: "model.tmp_var_0", "model.tmp_var_1", "model.tmp_var_2", "model.tmp_var_5", "model.tmp_var_6", "model.tmp_var_7", "model.tmp_var_8", "model.tmp_var_9". 
```

**Comment by ayaz-amin** [comment]
Found solution [here](https://github.com/VLL-HD/FrEIA/issues/10)
