### ISSUE TITLE
hidden `scipy` dependency

### ISSUE THREAD

**Issue by psteinb** [VLL-HD/FrEIA#60]
```
ImportError: Failed to import test module: test_base
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/runner/work/FrEIA/FrEIA/tests/test_base.py", line 11, in <module>
    from FrEIA.modules import InvertibleModule
  File "/home/runner/work/FrEIA/FrEIA/FrEIA/__init__.py", line 5, in <module>
    from . import modules
  File "/home/runner/work/FrEIA/FrEIA/FrEIA/modules/__init__.py", line 54, in <module>
    from .all_in_one_block import *
  File "/home/runner/work/FrEIA/FrEIA/FrEIA/modules/all_in_one_block.py", line 8, in <module>
    from scipy.stats import special_ortho_group
ModuleNotFoundError: No module named 'scipy'
```

`scipy` is required in `modules/all_in_one_block.py` but not contained in `requirements.txt`

**Comment by ardizzone** [comment]
Fixed by 3eea904
