### ISSUE TITLE
Running the code for the paper "Analyzing inverse problems with invertible neural networks"

### ISSUE THREAD

**Issue by Navid-visual** [VLL-HD/FrEIA#67]
When I run the code I get this error :

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/INN/Inn_8_modes mixture model.py", line 234, in <module>
    train(i_epoch)
  File "/home/INN/Inn_8_modes mixture model.py", line 155, in train
    output = model(x)
  File "/home/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/.local/lib/python3.7/site-packages/FrEIA/framework/reversible_graph_net.py", line 378, in forward
    results = self.module_list[o[0]](x, rev=rev)
  File "/home/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/.local/lib/python3.7/site-packages/FrEIA/modules/fixed_transforms.py", line 28, in forward
    return [x[0][:, self.perm]]
TypeError: tuple indices must be integers or slices, not tuple

**Comment by ardizzone** [comment]
Hi! I'm sorry, we merged some large changes into the main branch that aren't quite inter-compatible yet, in preparation for the release of version 0.3.
If you have FrEIA installed on your machine through pip, uninstall it,
then manually clone the repository, and checkout the previous v0.2 version, like so:

```bash
git clone https://github.com/VLL-HD/FrEIA.git
cd FrEIA
git checkout v0.2
python setup.py develop
```

Otherwise, we should have everything working again in a few days, I hope!
(Next time, we will use a development branch, sorry about this!)

**Comment by Navid-visual** [comment]
Thank you, now it is working.
