### ISSUE TITLE
FrEIA forward compatibility with older code base

### ISSUE THREAD

**Issue by aashishkumar0228** [VLL-HD/FrEIA#86]
I am trying to run the IB-INN repo ( https://github.com/VLL-HD/IB-INN ) with latest FrEIA framework. But getting the following error:

Traceback (most recent call last):
  File "/home/kaushikdas/aashish/FrEIA/FrEIA/framework/graph_inn.py", line 300, in forward
    mod_out = node.module(mod_in, rev=rev, jac=jac)
  File "/home/kaushikdas/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'jac'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 29, in <module>
    train.train(args)
  File "/home/kaushikdas/aashish/IB-INN/train.py", line 101, in train
    losses = inn(x, y)
  File "/home/kaushikdas/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kaushikdas/aashish/IB-INN/model.py", line 141, in forward
    z = self.inn(x)
  File "/home/kaushikdas/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/kaushikdas/aashish/FrEIA/FrEIA/framework/reversible_graph_net.py", line 36, in forward
    return super().forward(x_or_z, c, rev, jac, intermediate_outputs)
  File "/home/kaushikdas/aashish/FrEIA/FrEIA/framework/graph_inn.py", line 302, in forward
    raise RuntimeError(f"{node} encountered an error.") from e
RuntimeError: Node 'CONV_1_0': [(4, 14, 14)] -> AIO_Block -> [(4, 14, 14)] encountered an error.

Any fix for this?

**Comment by ardizzone** [comment]
Hi!
At the moment, the easiest thing would be to install the previous release version of FrEIA (v0.2), i.e.
```
git clone https://github.com/VLL-HD/FrEIA.git
cd FrEIA
git checkout v0.2
python setup.py develop
```

Thank you for bringing it up, I will push a fix to the IB-INN code to make it run with the newest version when I get the chance!

**Comment by aashishkumar0228** [comment]
Thanks for the reply. I was able to run the code by installing following version of FrEIA https://github.com/VLL-HD/FrEIA.git@c5fe1af0de8ce9122b5b61924ad75a19b9dc2473

**Comment by ardizzone** [comment]
Hi! Sorry for the late answer!

For now, see the readme of the IB-INN code of how to install the previous FrEIA version 0.2 (https://github.com/VLL-HD/IB-INN)
I will try to fix it to work with the current FrEIA at the next opportunity!
