### ISSUE TITLE
how to use reshape fuction

### ISSUE THREAD

**Issue by Christian-lyc** [VLL-HD/FrEIA#93]
Hi, thank you for your code, I have problem with using reshape function, I don't know how to write input dim ´´´dims_in´´´ there.

my piece of code is like this, ´´´Fm.Reshape(dims_in=1024,target_dim=(1,32,32)), {}, name='reshape')´´´ ,
but there is an error:  TypeError: 'int' object is not iterable. 
I don't know how to solve it. Could you help me? Thank you!

**Comment by psteinb** [comment]
Can you share the whole backtrace? My suspicion is that `dims_in=(1024,)` might already do the job? But I don't know the details and hence might suggest something totally irrelevant.

**Comment by Christian-lyc** [comment]
Hi, Peter, thank you for replying. 
here is the whole error:

Traceback (most recent call last):
  File "/home/yichao/Desktop/conditional_INNs/colorization_minimal_example/train.py", line 171, in <module>
    cinn = model.ColorizationCINN(1e-3)
  File "/home/yichao/Desktop/conditional_INNs/colorization_minimal_example/model.py", line 50, in __init__
    self.cinn = self.build_inn()
  File "/home/yichao/Desktop/conditional_INNs/colorization_minimal_example/model.py", line 105, in build_inn
    nodes.append(Ff.Node(nodes[-1], Fm.Reshape(dims_in=1024,target_dim=(1,32,32)), {}, name='reshape'))#
  File "/home/yichao/anaconda3/envs/cINN/lib/python3.7/site-packages/FrEIA/modules/reshapes.py", line 416, in __init__
    super().__init__(dims_in, dims_c)
  File "/home/yichao/anaconda3/envs/cINN/lib/python3.7/site-packages/FrEIA/modules/base.py", line 46, in __init__
    self.dims_in = list(dims_in)
TypeError: 'int' object is not iterable
